require 'rake'
require 'parallel'
require 'cucumber/rake/task'


ENV['chrome'] ||= 'true'
ENV['environ'] ||= 'https://twitter.com/login'
Cucumber::Rake::Task.new(:single) do |task|
  # task.cucumber_opts = ['--format=html','--out report.html', '--tags @run', 'features/signin.feature']
  task.cucumber_opts = ['--format=pretty', 'features/signin.feature']
end

task default: :single

Cucumber::Rake::Task.new(:local) do |task|
  task.cucumber_opts = ['--format=pretty', 'features/signin.feature', 'CONFIG_NAME=local']
end

task :parallel do |_t, _args|
  @num_parallel = 4

  Parallel.map([*1..@num_parallel], in_processes: @num_parallel) do |task_id|
    ENV['TASK_ID'] = (task_id - 1).to_s
    ENV['name'] = 'parallel_test'
    ENV['CONFIG_NAME'] = 'parallel'

    Rake::Task['single'].invoke
    Rake::Task['single'].reenable
  end
end

task :test do |_t, _args|
  Rake::Task['single'].invoke
  Rake::Task['single'].reenable
  Rake::Task['local'].invoke
  Rake::Task['parallel'].invoke
end

